---

#  This is a YAML configuration file.  To see yaml file specification, see its
#  wikipedia page at http://en.wikipedia.org/wiki/YAML


#  The port where the service will run
Port: 8000

#  The address where the service will run.  If you wish to run it on your computer, you
#  should use `localhost`.  If you wish to share the service on your local network, you
#  should use `0.0.0.0`
ServingAddress: localhost

#  The list of mongo servers.  Each server is an object with a field *name* that will
#  be shown in the web user interface and a *url* field that points to the mongo server
MongoServers:
    -
      name: localhost
      url: localhost:27017
    -
      name: mongolab
      url: mongodb://ustraca:9OApiiV9En85bBFGfVyYKH4C@ds049288.mongolab.com:49288/ustraca
